[package]
name = "gday_contact_exchange_protocol"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "Protocol that peers can use to exchange their public and private socket addresses via a server."
license = "MIT"
repository = "https://github.com/manforowicz/gday/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.38.0", features = ["test-util", "macros"] }
