[package]
name = "gday_contact_exchange_protocol"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "Protocol that peers can use to exchange their public and private socket addresses via a server."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1.36.0", features = ["test-util", "macros"] }
