[package]
name = "gday_file_transfer"
version = "0.1.1"
description = "A minimal protocol to securely transfer files over an IO stream. Used by gday."

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gday_encryption = { version = "0.1.1", path = "../gday_encryption" }
os_str_bytes = "7.0.0"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
thiserror = "1.0.61"
