[package]
name = "gday_file_transfer"
version = "0.1.1"
description = "Protocol to securely transfer files over an encrypted IO stream."
homepage = "https://github.com/manforowicz/gday/tree/main/gday_file_transfer"
categories = ["network-programming"]

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
os_str_bytes = "7.0.0"
rand = "0.8.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
thiserror = "1.0.61"

[dev-dependencies]
tempfile = "3.10.1"
