[package]
name = "gday_hole_punch"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "Establish an authenticated peer-to-peer internet connection using TCP hole-punching."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.1"
gday_contact_exchange_protocol = { version = "0.1.0", path = "../gday_contact_exchange_protocol" }
log = "0.4.21"
rand = "0.8.5"
rustls = "0.23.9"
serde = "1.0.203"
socket2 = "0.5.7"
spake2 = { version = "0.4.0", features = ["std"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["net", "rt", "time"] }
webpki-roots = "0.26.2"
