[package]
name = "gday_hole_punch"
version = "0.1.1"
description = "Establish an authenticated peer-to-peer internet connection using TCP hole-punching."

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.1"
gday_contact_exchange_protocol = { version = "0.1.1", path = "../gday_contact_exchange_protocol" }
log = "0.4.21"
rand = "0.8.5"
rustls = { version = "0.23.9", features = ["ring", "log", "logging", "std", "tls12"], default-features = false }
serde = "1.0.203"
socket2 = "0.5.7"
spake2 = { version = "0.4.0", features = ["std"] }
thiserror = "1.0.61"
tokio = { version = "1.38.0", features = ["net", "rt", "time"] }
webpki-roots = "0.26.2"
