[package]
name = "gday_hole_punch"
version = "0.1.0"
edition = "2021"
authors = ["Marcin Anforowicz"]
description = "A simple ChaCha20Poly1305 encryption wrapper around an async IO stream."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.1"
futures = "0.3.30"
gday_contact_exchange_protocol = { version = "0.1.0", path = "../gday_contact_exchange_protocol" }
hkdf = "0.12.4"
log = "0.4.21"
rand = "0.8.5"
rustls = "0.22.2"
socket2 = "0.5.6"
spake2 = { version = "0.4.0", features = ["std"] }
thiserror = "1.0.58"
tokio = { version = "1.36.0", features = ["net"] }
webpki-roots = "0.26.1"
