[package]
name = "gday_encryption"
version = "0.2.0"
description = "Simple encrypted ChaCha20Poly1305 wrapper around an IO stream."
homepage = "https://github.com/manforowicz/gday/tree/main/gday_encryption"
categories = ["cryptography"]

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8.5"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "benchmark"
harness = false
