[package]
name = "gday_encryption"
version = "0.1.1"
description = "A simple ChaCha20Poly1305 encryption wrapper around an IO stream."
homepage = "https://github.com/manforowicz/gday/gday_encryption/"

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "benchmark"
harness = false
