[package]
name = "gday_encryption"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "A simple ChaCha20Poly1305 encryption wrapper around an IO stream."
license = "MIT"
repository = "https://github.com/manforowicz/gday/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }

[dev-dependencies]
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "benchmark"
harness = false
