[package]
name = "gday"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "Command line tool to send files easily, securely, and directly, without a relay or port forwarding."
license = "MIT"
repository = "https://github.com/manforowicz/gday/"

[package.metadata.wix]
upgrade-guid = "FCAEFC4D-05CD-4DCB-B03B-8A166EDF4E86"
path-guid = "CB3BA61F-1F31-4F17-9778-D5BBAA9697DF"
license = false
eula = false
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11.3"
gday_encryption = { version = "0.1.0", path = "../gday_encryption" }
gday_file_transfer = { version = "0.1.0", path = "../gday_file_transfer" }
gday_hole_punch = { version = "0.1.0", path = "../gday_hole_punch" }
indicatif = "0.17.8"
log = "0.4.21"
os_str_bytes = "7.0.0"
owo-colors = "4.0.0"
postcard = "1.0.8"
rand = "0.8.5"
serde = { version = "1.0.203", features = ["serde_derive"] }
thiserror = "1.0.61"

[dev-dependencies]
assert_cmd = "2.0.14"
gday_server = { version = "0.1.0", path = "../gday_server" }
tempfile = "3.10.1"
