[package]
name = "gday"
version = "0.1.0"
edition = "2021"
authors = ["Marcin Anforowicz"]
description = "Command line tool to easily send files directly and securely to peers, without port forwarding or relays."
license = "MIT"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
env_logger = "0.11.3"
gday_encryption = { version = "0.1.0", path = "../gday_encryption" }
gday_file_offer_protocol = { version = "0.1.0", path = "../gday_file_offer_protocol" }
gday_hole_punch = { version = "0.1.0", path = "../gday_hole_punch" }
indicatif = "0.17.8"
log = "0.4.21"
os_str_bytes = "7.0.0"
owo-colors = "4.0.0"
postcard = "1.0.8"
rand = "0.8.5"
serde = { version = "1.0.197", features = ["serde_derive"] }
thiserror = "1.0.58"
