[package]
name = "gday_server"
version = "0.1.1"
description = "A server that lets 2 peers exchange their private and public addresses via the gday contact exchange protocol."

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
socket2 = "0.5.7"
tokio = { version = "1.38.0", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "sync",
] }
tokio-rustls = { version = "0.26.0", features = ["ring", "logging", "tls12"], default-features = false }
gday_contact_exchange_protocol = { path = "../gday_contact_exchange_protocol" }
thiserror = "1.0.61"
log = "0.4.21"
env_logger = "0.11.3"
rustls-pemfile = "2.1.2"
