[package]
name = "gday_server"
version = "0.1.0"
authors = ["Marcin Anforowicz"]
edition = "2021"
description = "A server that lets 2 peers exchange their private and public addresses via the gday contact exchange protocol."
license = "MIT"
repository = "https://github.com/manforowicz/gday/"

[package.metadata.wix]
upgrade-guid = "C41E4AFE-47F3-4089-8040-B2FFF4135772"
path-guid = "6EC3598B-2B5A-47EF-854A-401AB20270D2"
license = false
eula = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
socket2 = "0.5.7"
tokio = { version = "1.38.0", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "sync",
] }
tokio-rustls = "0.26.0"
gday_contact_exchange_protocol = { path = "../gday_contact_exchange_protocol" }
thiserror = "1.0.61"
log = "0.4.21"
env_logger = "0.11.3"
rustls-pemfile = "2.1.2"
