[package]
name = "gday_server"
version = "0.1.1"
description = "Server that lets 2 peers exchange their socket addresses."
homepage = "https://github.com/manforowicz/gday/tree/main/gday_server"
categories = ["command-line-utilities"]

# Inherit these keys from workspace toml
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.6", features = ["derive"] }
socket2 = { version = "0.5.7", features = ["all"] }
tokio = { version = "1.38.0", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "time",
    "sync",
] }
tokio-rustls = { version = "0.26.0", features = ["ring", "logging", "tls12"], default-features = false }
gday_contact_exchange_protocol = { version = "0.1.1", path = "../gday_contact_exchange_protocol" }
thiserror = "1.0.61"
log = "0.4.21"
env_logger = "0.11.3"
rustls-pemfile = "2.1.2"
