# GitHub workflow which runs on pushes.
# Does a build and test with stable Rust on 3 different platforms.

name: Stable Build & Test

on:
  push:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Stable Build & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v3

      - name: Update rustup
        run: rustup update

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
