name: Cargo Build & Test

on:
  push:
    branches:
      - main
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - uses: actions/checkout@v3

      - name: Update rutup
        run: rustup update stable && rustup default stable

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Clippy
        run: cargo clippy --verbose

      - name: Check documentation 
        run: cargo doc --no-deps --verbose

      - name: Check formatting
        run: cargo fmt --check --verbose
